//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_Proyecto_Grupo_6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compra
    {
        public int CompraId { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Destino { get; set; }
        public Nullable<int> Price { get; set; }
    }
}
